# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29fb46872f5e79f52ee877241124a986281b550b64f612cf458c3de9ba082c4d16d9ef397c0f9a8df769524a1352610b3c81926efda0fe1d7fe6a39f25546072

test:
  secret_key_base: c612a56a67c493605cc533ef3a6129857f0f9bf1bef2f76ccaf3488599d2a13f930622e5877d373a7f09bbeba8366d7a40fa25d3dabc3296160d7a864159faf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
